console.log("js loaded");

/* set up variables */
var leagueData = {
  "Seasons": [
    {
      "SeasonNumber": 1,
      "Games": [
        {
          "Stadium": "Bowser's Castle",
          "AwayTeam": "Lazy Lurkers",
          "HomeTeam": "Sacramento Kings",
          "AwayScore": 1,
          "HomeScore": 9,
          "InningsPlayed": 9,
          "Date": "03-10-2022 3:50AM"
        },
        {
          "Stadium": "Yoshi's Island",
          "AwayTeam": "Sacramento Kings",
          "HomeTeam": "Brick Squad",
          "AwayScore": 4,
          "HomeScore": 9,
          "InningsPlayed": 9,
          "Date": "03-13-2022 7:03PM"
        },
        {
          "Stadium": "Peach's Garden",
          "AwayTeam": "Brick Squad",
          "HomeTeam": "Battle Toads?",
          "AwayScore": 21,
          "HomeScore": 0,
          "InningsPlayed": 4,
          "Date": "03-09-2022 7:24PM"
        },
        {
          "Stadium": "DK's Jungle",
          "AwayTeam": "Bus Stop Gang",
          "HomeTeam": "Sunshine Strikers",
          "AwayScore": 8,
          "HomeScore": 9,
          "InningsPlayed": 9,
          "Date": "03-08-2022 7:31PM"
        }
      ],
      "Teams": [
        {
          "TeamName": "Lazy Lurkers",
          "TeamCaptain": "Luigi",
          "HomeStadium": "Mario Stadium",
          "GamesWon": 0,
          "GamesLost": 1,
          "TotalScore": 1,
          "BattersFaced": 41,
          "RunsAllowed": 9,
          "BattersWalked": 0,
          "BattersHit": 2,
          "HitsAllowed": 13,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 100,
          "StrikeoutsThrown": 8,
          "OutsPitched": 23,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 9,
          "ERA": 9.0,
          "AtBats": 35,
          "Hits": 11,
          "Singles": 8,
          "Doubles": 3,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 5,
          "BallWalks": 0,
          "HitWalks": 1,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 7,
          "BattingAVG": 0.31,
          "OBP": 0.33,
          "SLG": 0.4,
          "OPS": 0.73
        },
        {
          "TeamName": "Sacramento Kings",
          "TeamCaptain": "Bowser",
          "HomeStadium": "Bowser Castle",
          "GamesWon": 1,
          "GamesLost": 1,
          "TotalScore": 13,
          "BattersFaced": 80,
          "RunsAllowed": 10,
          "BattersWalked": 1,
          "BattersHit": 1,
          "HitsAllowed": 32,
          "HomeRunsAllowed": 1,
          "PitchesThrown": 165,
          "StrikeoutsThrown": 11,
          "OutsPitched": 51,
          "StarPitchesThrown": 1,
          "BigPlays": 1,
          "InningsPitched": 18,
          "ERA": 5.0,
          "AtBats": 70,
          "Hits": 22,
          "Singles": 14,
          "Doubles": 6,
          "Triples": 2,
          "Homeruns": 0,
          "StrikeoutsSwung": 14,
          "BallWalks": 0,
          "HitWalks": 2,
          "RunsBattedIn": 13,
          "BasesStolen": 3,
          "StarHits": 5,
          "BattingAVG": 0.31,
          "OBP": 0.33,
          "SLG": 0.46,
          "OPS": 0.79
        },
        {
          "TeamName": "Brick Squad",
          "TeamCaptain": "Yoshi",
          "HomeStadium": "Yoshi Park",
          "GamesWon": 2,
          "GamesLost": 0,
          "TotalScore": 30,
          "BattersFaced": 49,
          "RunsAllowed": 4,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 13,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 107,
          "StrikeoutsThrown": 12,
          "OutsPitched": 39,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 13,
          "ERA": 2.77,
          "AtBats": 80,
          "Hits": 47,
          "Singles": 33,
          "Doubles": 8,
          "Triples": 4,
          "Homeruns": 2,
          "StrikeoutsSwung": 8,
          "BallWalks": 1,
          "HitWalks": 0,
          "RunsBattedIn": 28,
          "BasesStolen": 0,
          "StarHits": 2,
          "BattingAVG": 0.59,
          "OBP": 0.59,
          "SLG": 0.86,
          "OPS": 1.46
        },
        {
          "TeamName": "Battle Toads?",
          "TeamCaptain": "Peach",
          "HomeStadium": "Peach Garden",
          "GamesWon": 0,
          "GamesLost": 1,
          "TotalScore": 0,
          "BattersFaced": 41,
          "RunsAllowed": 21,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 26,
          "HomeRunsAllowed": 1,
          "PitchesThrown": 82,
          "StrikeoutsThrown": 2,
          "OutsPitched": 12,
          "StarPitchesThrown": 6,
          "BigPlays": 6,
          "InningsPitched": 4,
          "ERA": 47.25,
          "AtBats": 16,
          "Hits": 4,
          "Singles": 4,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 6,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.25,
          "OBP": 0.25,
          "SLG": 0.25,
          "OPS": 0.5
        },
        {
          "TeamName": "Bus Stop Gang",
          "TeamCaptain": "Wario",
          "HomeStadium": "Wario Palace",
          "GamesWon": 0,
          "GamesLost": 1,
          "TotalScore": 8,
          "BattersFaced": 43,
          "RunsAllowed": 8,
          "BattersWalked": 0,
          "BattersHit": 5,
          "HitsAllowed": 14,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 88,
          "StrikeoutsThrown": 10,
          "OutsPitched": 25,
          "StarPitchesThrown": 1,
          "BigPlays": 1,
          "InningsPitched": 9,
          "ERA": 8.0,
          "AtBats": 42,
          "Hits": 17,
          "Singles": 13,
          "Doubles": 4,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 10,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 8,
          "BasesStolen": 0,
          "StarHits": 7,
          "BattingAVG": 0.4,
          "OBP": 0.4,
          "SLG": 0.5,
          "OPS": 0.9
        },
        {
          "TeamName": "Sunshine Strikers",
          "TeamCaptain": "DK",
          "HomeStadium": "Donkey Kong Jungle",
          "GamesWon": 1,
          "GamesLost": 0,
          "TotalScore": 9,
          "BattersFaced": 44,
          "RunsAllowed": 8,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 17,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 97,
          "StrikeoutsThrown": 10,
          "OutsPitched": 26,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 9,
          "ERA": 8.0,
          "AtBats": 38,
          "Hits": 14,
          "Singles": 9,
          "Doubles": 5,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 10,
          "BallWalks": 0,
          "HitWalks": 5,
          "RunsBattedIn": 8,
          "BasesStolen": 0,
          "StarHits": 5,
          "BattingAVG": 0.37,
          "OBP": 0.44,
          "SLG": 0.5,
          "OPS": 0.94
        }
      ],
      "Characters": [
        {
          "CharacterName": "Bowser",
          "IsCaptain": true,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 9,
          "Hits": 1,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 1,
          "Homeruns": 0,
          "StrikeoutsSwung": 3,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 3,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.11,
          "OBP": 0.11,
          "SLG": 0.33,
          "OPS": 0.44
        },
        {
          "CharacterName": "Bro(F)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 8,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 4,
          "BallWalks": 0,
          "HitWalks": 1,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.12,
          "OBP": 0.22,
          "SLG": 0.12,
          "OPS": 0.35
        },
        {
          "CharacterName": "Magikoopa(G)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 34,
          "RunsAllowed": 2,
          "BattersWalked": 1,
          "BattersHit": 0,
          "HitsAllowed": 13,
          "HomeRunsAllowed": 1,
          "PitchesThrown": 76,
          "StrikeoutsThrown": 6,
          "OutsPitched": 22,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 8,
          "ERA": 2.25,
          "AtBats": 9,
          "Hits": 1,
          "Singles": 0,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.11,
          "OBP": 0.11,
          "SLG": 0.22,
          "OPS": 0.33
        },
        {
          "CharacterName": "King Boo",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 8,
          "Hits": 4,
          "Singles": 2,
          "Doubles": 2,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 1,
          "RunsBattedIn": 3,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.56,
          "SLG": 0.75,
          "OPS": 1.31
        },
        {
          "CharacterName": "Pianta(Y)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 9,
          "Hits": 3,
          "Singles": 2,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.33,
          "OBP": 0.33,
          "SLG": 0.44,
          "OPS": 0.78
        },
        {
          "CharacterName": "Dry Bones(R)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 8,
          "Hits": 4,
          "Singles": 4,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 2,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.5,
          "OPS": 1.0
        },
        {
          "CharacterName": "Shy Guy(B)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 3,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 6,
          "StrikeoutsThrown": 0,
          "OutsPitched": 3,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 1,
          "ERA": 0.0,
          "AtBats": 4,
          "Hits": 3,
          "Singles": 3,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 1,
          "StarHits": 1,
          "BattingAVG": 0.75,
          "OBP": 0.75,
          "SLG": 0.75,
          "OPS": 1.5
        },
        {
          "CharacterName": "Dixie",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 43,
          "RunsAllowed": 8,
          "BattersWalked": 0,
          "BattersHit": 1,
          "HitsAllowed": 19,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 83,
          "StrikeoutsThrown": 5,
          "OutsPitched": 26,
          "StarPitchesThrown": 1,
          "BigPlays": 1,
          "InningsPitched": 9,
          "ERA": 8.0,
          "AtBats": 6,
          "Hits": 3,
          "Singles": 1,
          "Doubles": 2,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 1,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.83,
          "OPS": 1.33
        },
        {
          "CharacterName": "Koopa(R)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 3,
          "Hits": 1,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 1,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 5,
          "BasesStolen": 1,
          "StarHits": 2,
          "BattingAVG": 0.33,
          "OBP": 0.33,
          "SLG": 1.0,
          "OPS": 1.33
        },
        {
          "CharacterName": "Paratroopa(G)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 3,
          "Singles": 2,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 2,
          "BattingAVG": 0.75,
          "OBP": 0.75,
          "SLG": 1.0,
          "OPS": 1.75
        },
        {
          "CharacterName": "Magikoopa(B)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Toad(G)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.25,
          "OBP": 0.25,
          "SLG": 0.25,
          "OPS": 0.5
        },
        {
          "CharacterName": "Petey",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 3,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 1,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.0,
          "OBP": 0.25,
          "SLG": 0.0,
          "OPS": 0.25
        },
        {
          "CharacterName": "Dry Bones(G)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 2,
          "Singles": 1,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.75,
          "OPS": 1.25
        },
        {
          "CharacterName": "Luigi",
          "IsCaptain": true,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 2,
          "Singles": 2,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 2,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.5,
          "OPS": 1.0
        },
        {
          "CharacterName": "Shy Guy(Bk)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Goomba",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 41,
          "RunsAllowed": 9,
          "BattersWalked": 0,
          "BattersHit": 2,
          "HitsAllowed": 13,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 100,
          "StrikeoutsThrown": 8,
          "OutsPitched": 23,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 8,
          "ERA": 10.12,
          "AtBats": 4,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.25,
          "OBP": 0.25,
          "SLG": 0.25,
          "OPS": 0.5
        },
        {
          "CharacterName": "Shy Guy(Y)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 2,
          "Singles": 1,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.75,
          "OPS": 1.25
        },
        {
          "CharacterName": "Mario",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 8,
          "Hits": 7,
          "Singles": 2,
          "Doubles": 4,
          "Triples": 0,
          "Homeruns": 1,
          "StrikeoutsSwung": 0,
          "BallWalks": 1,
          "HitWalks": 0,
          "RunsBattedIn": 4,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.88,
          "OBP": 0.89,
          "SLG": 1.75,
          "OPS": 2.64
        },
        {
          "CharacterName": "Yoshi",
          "IsCaptain": true,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 9,
          "Hits": 4,
          "Singles": 3,
          "Doubles": 0,
          "Triples": 1,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 3,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.44,
          "OBP": 0.44,
          "SLG": 0.67,
          "OPS": 1.11
        },
        {
          "CharacterName": "Birdo",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 10,
          "Hits": 6,
          "Singles": 3,
          "Doubles": 1,
          "Triples": 1,
          "Homeruns": 1,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 7,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.6,
          "OBP": 0.6,
          "SLG": 1.2,
          "OPS": 1.8
        },
        {
          "CharacterName": "Shy Guy(G)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 9,
          "Hits": 5,
          "Singles": 5,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 2,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.56,
          "OBP": 0.56,
          "SLG": 0.56,
          "OPS": 1.11
        },
        {
          "CharacterName": "Baby Mario",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 8,
          "Hits": 5,
          "Singles": 5,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 3,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.62,
          "OBP": 0.62,
          "SLG": 0.62,
          "OPS": 1.25
        },
        {
          "CharacterName": "Daisy",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 33,
          "RunsAllowed": 4,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 9,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 69,
          "StrikeoutsThrown": 6,
          "OutsPitched": 27,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 9,
          "ERA": 4.0,
          "AtBats": 10,
          "Hits": 4,
          "Singles": 2,
          "Doubles": 2,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 2,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.4,
          "OBP": 0.4,
          "SLG": 0.6,
          "OPS": 1.0
        },
        {
          "CharacterName": "Paratroopa(R)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 9,
          "Hits": 6,
          "Singles": 5,
          "Doubles": 0,
          "Triples": 1,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 3,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.67,
          "OBP": 0.67,
          "SLG": 0.89,
          "OPS": 1.56
        },
        {
          "CharacterName": "Dry Bones(B)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 9,
          "Hits": 7,
          "Singles": 6,
          "Doubles": 0,
          "Triples": 1,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 2,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.78,
          "OBP": 0.78,
          "SLG": 1.0,
          "OPS": 1.78
        },
        {
          "CharacterName": "Waluigi",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 16,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 4,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 38,
          "StrikeoutsThrown": 6,
          "OutsPitched": 12,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 4,
          "ERA": 0.0,
          "AtBats": 8,
          "Hits": 3,
          "Singles": 2,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 2,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.38,
          "OBP": 0.38,
          "SLG": 0.5,
          "OPS": 0.88
        },
        {
          "CharacterName": "Dry Bones(Gy)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 4,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 1,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 8,
          "StrikeoutsThrown": 2,
          "OutsPitched": 2,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 1,
          "ERA": 0.0,
          "AtBats": 8,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.12,
          "OBP": 0.12,
          "SLG": 0.12,
          "OPS": 0.25
        },
        {
          "CharacterName": "Koopa(G)",
          "IsCaptain": false,
          "GamesPlayed": 2,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 8,
          "Hits": 4,
          "Singles": 3,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.62,
          "OPS": 1.12
        },
        {
          "CharacterName": "Toadette",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 2,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.5,
          "OPS": 1.0
        },
        {
          "CharacterName": "Toad(P)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 2,
          "Hits": 2,
          "Singles": 2,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 1.0,
          "OBP": 1.0,
          "SLG": 1.0,
          "OPS": 2.0
        },
        {
          "CharacterName": "Toadsworth",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 11,
          "RunsAllowed": 7,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 5,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 23,
          "StrikeoutsThrown": 0,
          "OutsPitched": 4,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 2,
          "ERA": 31.5,
          "AtBats": 2,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Toad(R)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 12,
          "RunsAllowed": 10,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 10,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 23,
          "StrikeoutsThrown": 0,
          "OutsPitched": 2,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 1,
          "ERA": 90.0,
          "AtBats": 2,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Peach",
          "IsCaptain": true,
          "GamesPlayed": 1,
          "BattersFaced": 12,
          "RunsAllowed": 2,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 6,
          "HomeRunsAllowed": 1,
          "PitchesThrown": 23,
          "StrikeoutsThrown": 1,
          "OutsPitched": 5,
          "StarPitchesThrown": 6,
          "BigPlays": 6,
          "InningsPitched": 3,
          "ERA": 6.0,
          "AtBats": 2,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Toad(B)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 2,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Paragoomba",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 6,
          "RunsAllowed": 2,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 5,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 13,
          "StrikeoutsThrown": 1,
          "OutsPitched": 1,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 1,
          "ERA": 18.0,
          "AtBats": 2,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Toad(Y)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 1,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 1.0,
          "OBP": 1.0,
          "SLG": 1.0,
          "OPS": 2.0
        },
        {
          "CharacterName": "Baby Luigi",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 1,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Boo",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 39,
          "RunsAllowed": 8,
          "BattersWalked": 0,
          "BattersHit": 5,
          "HitsAllowed": 13,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 80,
          "StrikeoutsThrown": 8,
          "OutsPitched": 23,
          "StarPitchesThrown": 1,
          "BigPlays": 1,
          "InningsPitched": 9,
          "ERA": 8.0,
          "AtBats": 5,
          "Hits": 2,
          "Singles": 1,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 3,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.4,
          "OBP": 0.4,
          "SLG": 0.6,
          "OPS": 1.0
        },
        {
          "CharacterName": "Wario",
          "IsCaptain": true,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 3,
          "Singles": 3,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 2,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.6,
          "OBP": 0.6,
          "SLG": 0.6,
          "OPS": 1.2
        },
        {
          "CharacterName": "Noki(R)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 3,
          "BattingAVG": 0.2,
          "OBP": 0.2,
          "SLG": 0.2,
          "OPS": 0.4
        },
        {
          "CharacterName": "Pianta(R)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.2,
          "OBP": 0.2,
          "SLG": 0.2,
          "OPS": 0.4
        },
        {
          "CharacterName": "Magikoopa(R)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 4,
          "Singles": 2,
          "Doubles": 2,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 2,
          "BattingAVG": 0.8,
          "OBP": 0.8,
          "SLG": 1.2,
          "OPS": 2.0
        },
        {
          "CharacterName": "Bro(H)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.2,
          "OBP": 0.2,
          "SLG": 0.2,
          "OPS": 0.4
        },
        {
          "CharacterName": "Monty",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 2,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.5,
          "OPS": 1.0
        },
        {
          "CharacterName": "Diddy",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 37,
          "RunsAllowed": 8,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 16,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 79,
          "StrikeoutsThrown": 7,
          "OutsPitched": 22,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 8,
          "ERA": 9.0,
          "AtBats": 5,
          "Hits": 2,
          "Singles": 1,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.4,
          "OBP": 0.4,
          "SLG": 0.6,
          "OPS": 1.0
        },
        {
          "CharacterName": "DK",
          "IsCaptain": true,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 2,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 3,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.0,
          "OBP": 0.6,
          "SLG": 0.0,
          "OPS": 0.6
        },
        {
          "CharacterName": "Bro(B)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 1,
          "Singles": 1,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 1,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.25,
          "OBP": 0.4,
          "SLG": 0.25,
          "OPS": 0.65
        },
        {
          "CharacterName": "Noki(B)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 3,
          "Singles": 2,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 2,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.6,
          "OBP": 0.6,
          "SLG": 0.8,
          "OPS": 1.4
        },
        {
          "CharacterName": "Noki(G)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 7,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 1,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 18,
          "StrikeoutsThrown": 3,
          "OutsPitched": 4,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 2,
          "ERA": 0.0,
          "AtBats": 4,
          "Hits": 1,
          "Singles": 0,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 1,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 4,
          "BattingAVG": 0.25,
          "OBP": 0.4,
          "SLG": 0.5,
          "OPS": 0.9
        },
        {
          "CharacterName": "Pianta(B)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 2,
          "Singles": 2,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 1,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.4,
          "OBP": 0.4,
          "SLG": 0.4,
          "OPS": 0.8
        },
        {
          "CharacterName": "Shy Guy(R)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 5,
          "Hits": 3,
          "Singles": 2,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 0,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 3,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.6,
          "OBP": 0.6,
          "SLG": 0.8,
          "OPS": 1.4
        },
        {
          "CharacterName": "Magikoopa(Y)",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 0,
          "Singles": 0,
          "Doubles": 0,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 2,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 1,
          "BattingAVG": 0.0,
          "OBP": 0.0,
          "SLG": 0.0,
          "OPS": 0.0
        },
        {
          "CharacterName": "Bowser Jr",
          "IsCaptain": false,
          "GamesPlayed": 1,
          "BattersFaced": 0,
          "RunsAllowed": 0,
          "BattersWalked": 0,
          "BattersHit": 0,
          "HitsAllowed": 0,
          "HomeRunsAllowed": 0,
          "PitchesThrown": 0,
          "StrikeoutsThrown": 0,
          "OutsPitched": 0,
          "StarPitchesThrown": 0,
          "BigPlays": 0,
          "InningsPitched": 0,
          "ERA": -1.0,
          "AtBats": 4,
          "Hits": 2,
          "Singles": 1,
          "Doubles": 1,
          "Triples": 0,
          "Homeruns": 0,
          "StrikeoutsSwung": 1,
          "BallWalks": 0,
          "HitWalks": 0,
          "RunsBattedIn": 0,
          "BasesStolen": 0,
          "StarHits": 0,
          "BattingAVG": 0.5,
          "OBP": 0.5,
          "SLG": 0.75,
          "OPS": 1.25
        }
      ]
    }
  ]
};
var tableContents = leagueData.Seasons[0].Games;

/* load json file */
/*fetch("LeagueData.json")
	.then(response => response.json())
	.then(data => {
		console.log(data)
		leagueData = data
		tableContents = data.Seasons[0].Games
		buildTable(tableContents)
		setStandings(data.Seasons[0].Teams)
	})*/
	
console.log("JSON loaded:");
console.log(leagueData);

/* build table for the first time */
buildTable(tableContents);
setStandings(leagueData.Seasons[0].Teams)

/* functions */

function setStandings(data)
{
	var standingsTableHeader = document.getElementById('standingstableheader')
	standingsTableHeader.innerHTML = '';
	
	var headerRow = `<tr>
		<th data-column="TeamName">Team</th>
		<th data-column="GamesWon">W</th>
		<th data-column="GamesLost">L</th>
	</tr>`
		
	standingsTableHeader.innerHTML += headerRow
	
	var standingsTableBody = document.getElementById('standingstablebody')
	standingsTableBody.innerHTML = '';
	
	for(var i = 0; i < data.length; i++)
	{
		var row = `<tr>
			<td>${data[i].TeamName}</td>
			<td>${data[i].GamesWon}</td>
			<td>${data[i].GamesLost}</td>
		</tr>`
		
		
		standingsTableBody.innerHTML += row
	}
}

function buildTable(data)
{
	console.log("building table")	
	
	/* create headers */
	var tableHeader = document.getElementById('tableheader')
	tableHeader.innerHTML = '';
		
	var headerRow = `<tr>
		<th data-column="HomeTeam">Home</th>
		<th data-column="HomeScore">Score(H)</th>
		<th data-column="AwayTeam">Away</th>
		<th data-column="AwayScore">Score(A)</th>
		<th data-column="InningsPlayed">Innings</th>
		<th data-column="Stadium">Stadium</th>
		<th data-column="Date">Date</th>
	</tr>`
		
		tableHeader.innerHTML += headerRow
		
	/* create rows */
	var tableBody = document.getElementById('tablebody')
	tableBody.innerHTML = ''
	
	for(var i = 0; i < data.length; i++)
	{
		var row = `<tr>
			<td>${data[i].HomeTeam}</td>
			<td>${data[i].HomeScore}</td>
			<td>${data[i].AwayTeam}</td>
			<td>${data[i].AwayScore}</td>
			<td>${data[i].InningsPlayed}</td>
			<td>${data[i].Stadium}</td>
			<td>${data[i].Date}</td>
		</tr>`
	
		tableBody.innerHTML += row
	}
}